name : CI/CD Pipeline
on:
  pull_request:
   branches:
    -main

jobs:
  build:
   runs on: ubuntu-latest

   steps:

   -name: Checkout Code
    uses: actions/checkout@v2


  -name: Set up Nod.js
   uses: actions/setup-node@v2
   with:
    node-version : 20

  -name: Install Dependencies
   run  : npm install && npx generate prisma 

  -name : Run tests
   run : npm run test


